POST http://localhost:4000/api/user/register
Content-Type: application/json

{
  "username": "newsssssds2",
  "email": "newsss33asd24@example.com",
  "phoneNumber": "7686760017",
  "password": "password123",
  "gender": "male",
  "dateOfBirth": {
    "month": "January",
    "day": 23,
    "year": 2002
  }
}
###
POST http://localhost:4000/api/user/login
Content-Type: application/json

{
  "email": "Admin@gmail.com",
  "password": "password123"
}
###
GET http://localhost:4000/api/user/allusers
Content-Type: application/json
###
POST  http://localhost:4000/api/report/create-Report
Content-Type: application/json

{
  "user": "6684551aa69847e4f670a236",
  "issueTitle": "changekygug lamp2",
  "priority": "medium2kjhkj",
  "location": "beirutlj",
  "description": "you must change lamp 2",
  "image": "http://example/lamp2.net"
}

###
GET http://localhost:4000/api/report/getAllReports
Content-Type: application/json
###
GET http://localhost:4000/api/user/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2OGRjNjdlYTlhYThlM2E0NDI2MDc1MiIsImlhdCI6MTcyMDU2NzQzMywiZXhwIjoxNzIzMTU5NDMzfQ.oFfP6O1GuGI_nE15940T1rQ42F1xsjNcXA0xAXA_7CQ
###
PUT http://localhost:4000/api/user/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ODQ1NjBhMzEwYzA3ZjA3ODM4MmZhYyIsImlhdCI6MTcyMDUzNTE5MCwiZXhwIjoxNzIzMTI3MTkwfQ.zLvTJ7zwffPsA98mEguhvDeyL7DAEP-XCI6wF5pfU_g

{
  "username": "aliadmin",
  "email": "admin@admin.com",
  "gender": "male",
  "isAdmin" :true,
  "dateOfBirth": {
    "month": "January",
    "day": 1,
    "year": 1990
  }
}

###
POST  http://localhost:4000/api/news/addNews
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2OGQ1MTBjOGZlOWNlNWZjZjlkZDQyMiIsImlhdCI6MTcyMDUzNzY3MSwiZXhwIjoxNzIzMTI5NjcxfQ.yA7MOFgmCBP4JVr7csNHCB0YxlvIFZUrR-JdA_2alPU

{
  "title": "New News Title 3",
  "tag": "Technology whatever 3",
  "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  "image": "https://example.com/news-image.jpg"
}


###
DELETE http://localhost:4000/api/news/deleteNews/668d55f3229cb71b906163ec
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2OGQ1MTBjOGZlOWNlNWZjZjlkZDQyMiIsImlhdCI6MTcyMDUzNzY3MSwiZXhwIjoxNzIzMTI5NjcxfQ.yA7MOFgmCBP4JVr7csNHCB0YxlvIFZUrR-JdA_2alPU


###

GET http://localhost:4000/api/news/getAllNews
Content-Type: application/json




###

POST http://localhost:4000/api/user/createNewAddAdmin
Content-Type: application/json

{
  "username": "Admin",
  "email": "Admin@gmail.com",
  "password": "password123",
  "isAdmin":true,
  "gender": "male",
  "dateOfBirth": {
    "month": "January",
    "day": 23,
    "year": 2002
  }
}